name: XsdChecker
description: Validate XML instance documents using XSD.

branding:
  icon: tool
  color: green

inputs:
  xsd:
    description: XSD file.
    required: false
    example: xsd/schema.xsd
  file:
    description: File to validate.
    required: false
    example: example.xml

  script:
    description: Script to run.
    required: false
    example: xc --xslt2 **/*.xslt

  script_path:
    description: Script path to run.
    required: false
    example: validate_xsd.sh

runs:
  using: docker
  image: 'docker://klakegg/xsdchecker:edge'
  args:
    - ${{ inputs.xsd }}
    - ${{ inputs.file }}
