name: Build

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build jar
      run: make jar

    - name: Build distribution
      run: make dist

    - name: Build native image
      run: make graal

    - name: Upload "JAR file"
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: target/xsdchecker.jar
        name: xsdchecker-${TAG}.jar
        label: JAR file
        type: application/java-archive

    - name: Upload "Executable (Linux 64bit)"
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: target/xsdchecker
        name: xsdchecker-${TAG}-linux-64bit
        label: Executable (Linux 64bit)
        type: application/x-executable

    - name: Upload "Distribution (zip)"
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: target/dist.zip
        name: xsdchecker-${TAG}.zip
        label: Distribution (zip)
        type: application/zip

    - name: Upload "Distribution (tar.gz)"
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: target/dist.tar.gz
        name: xsdchecker-${TAG}.tar.gz
        label: Distribution (tar.gz)
        type: application/x-tar