name: Publish

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build jar
      run: make jar

    - name: Build image
      run: make graal

    - uses: klakegg/github-upload@v0.9.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: target/xsdchecker.jar
        name: xsdchecker-${TAG}.jar
        label: JAR file
        type: application/java-archive

    - uses: klakegg/github-upload@v0.9.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: target/xsdchecker
        name: xsdchecker-${TAG}-linux-64bit
        label: Executable (Linux 64bit)
        type: application/x-executable
